# Generated by Django 4.1 on 2022-09-13 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_likes_follow_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes_count",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ManyToManyField(
                related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
